### ISSUE TITLE
libtimescale_core.a will this be opensourced in the future?

### ISSUE THREAD

**Issue by avinashGonsalves** [Decawave/mynewt-timescale-lib#1]

**Comment by pkettle** [comment]
Hi Avinash, 

The intent is not to opensource the algorithm collateral at this point. The decision is related to the associated support burden. Are you using Cortex-M class devices or do you need a library for an alternative architecture?

**Comment by avinashGonsalves** [comment]
Hi Paul,
Yes, this is for another architecture,  Xtensa class devices. 
Possible to share a copy without the support at this point?

**Comment by pkettle** [comment]
Can you point me to the gnu toolchain for the device? Is this already supported under the Mynewt framework?

**Comment by avinashGonsalves** [comment]
Its not under the mynewt framework.
For the toolchain, please refer this link: https://github.com/espressif/ESP8266_RTOS_SDK/releases/tag/v3.0
If you're finding it difficult to build, the steps are described here: https://github.com/esp8266/esp8266-wiki/wiki/Toolchain

**Comment by pkettle** [comment]
Hi Avinash, I have added the xtensa_lx106 build of the library to the refactor branch. You can find this at ./mynewt-timescale-lib/lib/timescale/src/libtimescale_core.a_xtensa. This branch will be merged with the master shortly.

**Comment by avinashGonsalves** [comment]
Thank you Paul, much appreciated.
