### ISSUE TITLE
Xtensa Library: dangerous relocation: call0: call target out of range

### ISSUE THREAD

**Issue by avinashGonsalves** [Decawave/mynewt-timescale-lib#2]
Hello Paul,

I'm getting the following errors when trying to link the libtimescale_core.a_xtensa
_/Users/pkettle/workspace/timescale-core/lib/srkf_dbl.c:346:(.text.srkf_dbl_init+0x545): dangerous relocation: call0: call target out of range: memset
/Users/pkettle/workspace/timescale-core/lib/srkf_dbl.c:348:(.text.srkf_dbl_init+0x556): dangerous relocation: call0: call target out of range: realloc
/Users/pkettle/workspace/timescale-core/lib/srkf_dbl.c:350:(.text.srkf_dbl_init+0x571): dangerous relocation: call0: call target out of range: memset_

The fix for this issue is to compile the library with the option "-mlongcalls" from this post:
https://www.esp32.com/viewtopic.php?t=549

Could i request you to do the same.

Thanks.

**Comment by pkettle** [comment]
Avinash, 
Per your coment I have change the C_FLAGS as follows; 

```
set(CMAKE_C_FLAGS   "${MCPU_FLAGS} ${VFP_FLAGS} -Wall -fno-builtin -std=gnu11 -fdata-sections -ffunction-sections -mtext-section-literals -mlongcalls" CACHE INTERNAL "c compiler flags")

set(CMAKE_CXX_FLAGS "${MCPU_FLAGS} ${VFP_FLAGS} -Wall -fno-builtin -fdata-sections -ffunction-sections -mtext-section-literals -mlongcalls" CACHE INTERNAL "cxx compiler flags")

set(CMAKE_ASM_FLAGS "${MCPU_FLAGS} -x assembler-with-cpp" CACHE INTERNAL "asm compiler flags")

set(CMAKE_EXE_LINKER_FLAGS "${MCPU_FLAGS} ${LD_FLAGS} -Wl,--gc-sections" CACHE INTERNAL "exe link flags")
```

You should find a new build of the library in the same refactor repo.

**Comment by avinashGonsalves** [comment]
Thanks, will check.

**Comment by avinashGonsalves** [comment]
Compile/Link successful. Closing issue.
