### ISSUE TITLE
Clock Sync in DWM1001-DEV boards

### ISSUE THREAD

**Issue by enessuren** [Decawave/mynewt-timescale-lib#4]
Hi everyone,

Our earlier work with freertos operating system had been. We are trying to determine the position with TDOA. The clock frequencies that should be the same were not the same. Due to this significant ppm difference between the cards, we could not perform the wireless clock synchronization process. We obtained this information with the timestamp data we received. we think this is ultimately a hardware problem. I want to ask, can this problem be solved with this library?

Best Regards
Enes

**Comment by pkettle** [comment]
Hi Enes, 
For TDOA to work accurately, you will require wired synchronization or wireless clock synchronization of your anchors. This library implements wireless clock synchronization. Moreover using the mynewt-dw1000-core in conjunction with the mynewt-timescale-core transformers all timestamps/clock into the master reference frame greatly simplifying the TDOA problem.
